baseURL = "https://kolesnyk.fr"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "Denys Kolesnyk"
description = "Le site personnel de Denys Kolesnyk"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Google Analytics
googleAnalyticsID = "UA-2473685-7"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
copyright = "Denys Kolesnyk 2018-{{ YEAR }}"