baseURL = "https://kolesnyk.fr/"
theme = "hugo-ivy"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    languageName = "EN"
    languageCode = "en-GB"
    title = "Denys Kolesnyk"
    weight = 1
    [languages.en.params]
      description = "Strategic Intelligence Analyst"
      footer = "&copy; Denys Kolesnyk 2019-{Year}"
  [languages.fr]
    languageName = "FR"
    languageCode = "fr-FR"
    title = "Denys Kolesnyk"
    weight = 2
    [languages.fr.params]
      description = "Analyste en intelligence stratégique"
      footer = "&copy; Denys Kolesnyk 2019-{Year}"

[languages.en.menu]
  [[languages.en.menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[languages.en.menu.main]]
    name = "Services"
    url = "/services/"
    weight = 3
  [[languages.en.menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 4
  [[languages.en.menu.main]]
    name = "Media"
    url = "/media/"
    weight = 5
  [[languages.en.menu.main]]
    name = "Contact"
    url = "mailto:contact@kolesnyk.fr"
    weight = 6

[languages.fr.menu]
  [[languages.fr.menu.main]]
    name = "À propos"
    url = "/fr/about/"
    weight = 2
  [[languages.fr.menu.main]]
    name = "Services"
    url = "/fr/services/"
    weight = 3
  [[languages.fr.menu.main]]
    name = "Blog"
    url = "/fr/post/"
    weight = 4
  [[languages.fr.menu.main]]
    name = "Médias"
    url = "/fr/media/"
    weight = 5
  [[languages.fr.menu.main]]
    name = "Contact"
    url = "mailto:contact@kolesnyk.fr"
    weight = 6

[params]
  highlightjsLang = ["latex"]
  highlightjsTheme = "github"
  highlightjsVersion = "11.7.0"
  favicon = "favicon.ico"
  ogImage = "/images/dk_pic.jpeg"

[markup]
  [markup.highlight]
    codeFences = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
