baseURL: "https://kolesnyk.fr/"
theme: "writeonlyhugo-theme"
languageCode: "en-us"

title: "Denys Kolesnyk"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Write-Only Hugo"
  description: "A simple, clean and straightforward blog theme."
  customtextFontFamily: "Metropolis"
  customheadingFontFamily: "EB Garamond"
  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"

menu:
  main:
    - identifier: "Accueil"
      name: "Accueil"
      url: "https://kolesnyk.fr/"
      weight: 1

    - identifier: "À propos"
      name: "À propos"
      url: "/a-propos/"
      weight: 2

    - identifier: "Médias"
      name: "Médias"
      url: "/medias/"
      weight: 3

    - identifier: "Contact"
      name: "Contact"
      url: "/contact/"
      weight: 4

taxonomies:
  categories: 
    - "categories"
  tags: 
    - "tags"