baseURL: "https://kolesnyk.fr/"
theme: "writeonlyhugo-theme"
languageCode: "en-us"

title: "dk"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Denys Kolesnyk"
  description: "Welcome to Denys Kolesnyk's web site"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"

taxonomies:
  categories: "categories"
  tags: "tags"
