baseURL = "https://kolesnyk.fr"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "Denys Kolesnyk"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Google Analytics 4
googleAnalyticsID = "G-QRCM1BX8HY"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

copyright = "2018-2021"